### ISSUE TITLE
bug when relative paths is used (and no "place")

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/clean-stacktrace-metadata#3]
e.g.

```
at ../../goo/bar.js:33:12
```

so `err.place` becames `....`, damn

**Comment by tunnckoCore** [comment]
failing test of `stacktrace-metadata` lib

```js
test('should work for stack that dont have "place" at some lines', function (done) {
  var msg = 'no place just filename, line and column'
  var err = new Error(msg)
  err.stack = [
    'Error: no place just filename, line and column',
    '    at /home/foo/bar.js:331:7'
  ].join('\n')

  var error = stacktraceMetadata(err, {
    relativePaths: false
  })
  test.strictEqual(error.place, '')
  done()
})
```

temporary made it working by passing `relativePaths: false`
